### ISSUE TITLE
Hardcoded redis configuration for datasketch.MinHashLSH

### ISSUE THREAD

**Issue by psrok1** [W3ndige/karton-similarity#1]
`"redis"` configuration should be derived from Karton configuration (`self.config.redis_config`). Currently it doesn't work in environments with different Redis server hostname (not karton-playground-alike)

https://github.com/W3ndige/karton-similarity/blob/98188fbb6f0224d788b2b507fbf94d7b5b22d5c8/karton/similarity/similarity.py#L85-L93

**Comment by W3ndige** [comment]
Good catch! Somehow I've missed that before publishing. :thinking:
